#!/usr/bin/env node

/**
 * Generate version.ts from package.json
 * Run this script after build to keep version in sync
 */

const fs = require('fs');
const path = require('path');

// Read package.json
const packageJsonPath = path.join(__dirname, '../package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

// Generate version.ts content
const versionFileContent = `// Auto-generated file - do not edit manually
// Generated by scripts/generate-version.js
export const VERSION = '${version}';
`;

// Write to src/app/version.ts
const versionFilePath = path.join(__dirname, '../src/app/version.ts');
fs.writeFileSync(versionFilePath, versionFileContent, 'utf8');

console.log(`✅ Generated version.ts with version ${version}`);
